version: '3.8'

services:
  web:
    restart: unless-stopped
    build: .
    volumes:
      - ./src:/app
    ports:
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
      - TESTENV=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8888
